version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - '3000:3000'
    networks: 
      - smart-network
    volumes:
      - ./:/home/app/code
      - /home/app/code/node_modules